auth:
  secret: changeit

ivana:
  data-dir: ./data
  compression-quality: 0.3

logging:
  level:
    io.ivana: debug

spring:
  datasource:
    url: ${database.jdbcUrl}
    username: ${database.username}
    password: ${database.password}

  liquibase:
    change-log: classpath:/db/changelog.yml

  mvc:
    throw-exception-if-no-handler-found: true

  servlet:
    multipart:
      max-file-size: 10GB
