auth:
  secret: changeit

spring:
  datasource:
    url: ${database.jdbcUrl}
    username: ${database.username}
    password: ${database.password}

  liquibase:
    change-log: classpath:/db/changelog.yml

  mvc:
    throw-exception-if-no-handler-found: true
