auth:
  secret: changeit

cors:
  origins:
    - http://localhost:4200

ivana:
  data-dir: \${user.home}/ivana
  compression-quality: 0.3

logging:
  level:
    io.ivana: debug

spring:
  datasource:
    url: ${database.jdbcUrl}
    username: ${database.username}
    password: ${database.password}

  liquibase:
    change-log: classpath:/db/changelog.yml

  servlet:
    multipart:
      max-file-size: 10GB
