version: '3'

services:
  postgresql:
    image: postgres:11
    environment:
      POSTGRES_DB: ivana
      POSTGRES_USER: ivana
      POSTGRES_PASSWORD: ivana
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
