name: CI

on:
  push:
    branches:
      - '*'

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest
    container:
      image: gradle:6.2-jdk11
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_DB: ivana
          POSTGRES_USER: ivana
          POSTGRES_PASSWORD: ivana
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v1
      - name: Buid
        run: gradle assemble -x ivana-webapp:assemble
      - name: Test
        run: gradle clean check -Pdatabase.host=postgres -Pdatabase.port=${{ job.services.postgres.ports[5432] }} -Pliquibase.runList=main -x ivana-webapp:check

  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.16
      - name: Install dependencies
        working-directory: ./webapp
        run: npm install
      - name: Lint
        working-directory: ./webapp
        run: npm run lint
      - name: Build
        working-directory: ./webapp
        run: npm run build
# TODO: Write tests! :D
#      - name: Test
#        working-directory: ./webapp
#        run: npm test -- --configuration=ci
# Not working on GitHub CI
#      - name: E2E
#        working-directory: ./webapp
#        run: npm run e2e -- --configuration=ci
